### PR TITLE
3.1.0 release prep

### PR DESCRIPTION
**Pull request by nkoenig**
[Changes](https://github.com/ignitionrobotics/ign-launch/compare/ignition-launch3_3.0.0...ign-launch3).

Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Review by adlarkin — COMMENTED** [review]
I don't see PR #68 in the changelog, but it's in the [branch comparison](https://github.com/ignitionrobotics/ign-launch/compare/ignition-launch3_3.0.0...ign-launch3) - would it be worth adding this to the changelog?

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
> I don't see PR #68 in the changelog, but it's in the branch comparison - would it be worth adding this to the changelog?

Probaby because it landed in 1.x, so it falls under the  "everything up to x.x.x" description.

**Comment by adlarkin** [comment]
> Probaby because it landed in 1.x, so it falls under the "everything up to x.x.x" description.

Looks like #68 was merged on 2020-10-26, but the latest `1.x` release was on 2020-09-25, and the latest `2.x` release was on 2020-10-14. So, #68 was merged after the latest `1.x` and `2.x` releases, which makes me think that this PR didn't land in `1.x` - is there something I'm missing here?

**Comment by nkoenig** [comment]
Thanks, I just added it in: 5edccf2c350bbb0a240dc1ff14f091a0e9e98647

**Review by adlarkin — APPROVED** [review]

**Comment by mjcarroll** [comment]
Oh, I see, it's on the 1.x branch but has not been released yet.  Now that we are generating changelogs at the time of release (vs time the feature is added), it's not in there.

**Comment by adlarkin** [comment]
> Oh, I see, it's on the 1.x branch but has not been released yet. Now that we are generating changelogs at the time of release (vs time the feature is added), it's not in there.

That's true, I just realized the race condition PR was merged into the `ign-launch1` branch, but we haven't had a `1.x` release since that merge, right? So does that mean this PR shouldn't be place as a part of `1.x` in the changelog? Should it be a part of `3.x` instead?

**Pull request merged**
