### PR TITLE
Update gtest for Windows compilation

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🎉 Enhancement

## Summary

Update gtest for Windows compilation. 

Part of this PR https://github.com/ignitionrobotics/ign-launch/pull/120

## Checklist
- [x] Signed all commits for DCO
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by mjcarroll** [comment]
Windows CI is failing 

```
CMake Error at src/msgs/CMakeLists.txt:1 (PROTOBUF_GENERATE_CPP):
  Unknown CMake command "PROTOBUF_GENERATE_CPP".
```

Is this something that will need to be done across all of the ignition libraries as well?

**Comment by ahcorde** [comment]
@mjcarroll 

I would say that windows CI should not compile.

> Is this something that will need to be done across all of the ignition libraries as well?

The other packages are able to run tests. I think `ign-launch` is the last one without windows support. I would say no.

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Review by mjcarroll — APPROVED** [review]

**Comment by mjcarroll** [comment]
`ign-gazebo3` is disabled on Windows CI currently, presumably because it doesn't build on Windows: https://build.osrfoundation.org/view/ign-citadel/job/ign_gazebo-ign-3-win/

Since Windows CI for `ign-launch` depends on gazebo correctly building, it's safe to say it will never pass here, and can be ignored.

**Comment by chapulina** [comment]
> it will never pass here, and can be ignored.

This should prevent Windows CI from being triggered for branches other than `main`: https://github.com/ignition-tooling/release-tools/pull/492

**Pull request merged**
