### PR TITLE
Port ign-launch to Windows

### PR DESCRIPTION
**Pull request by ahcorde**
# 🎉 New feature

Related issue https://github.com/ignitionrobotics/ign-launch/issues/89

## Summary

This PR is part of the port of `ign-launch` to Windows and a continuation of the work started by @j-rivero 

Right now it's compiling but some of the tests are commented out. The key class of this port is `Manager`.

## Test it

For now we can only test Manager_TEST

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
Thanks, @ahcorde !

> Right now it's compiling but some of the tests are commented out

It's perfectly fine to disable tests on Windows for this first pass. We can just get it compiling first, and address other issues later. 

What's left to open this PR for review? Is it just a general cleanup to make sure Linux and macOS are still working?

**Comment by ahcorde** [comment]
@chapulina this is ready for review, but we should add the windows job.

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
[Windows build](https://build.osrfoundation.org/job/ign_launch-pr-win/211/consoleFull#-6385599948ff58640-3599-4406-a210-216932f1748c) should be fixed with this PR https://github.com/ignitionrobotics/ign-transport/pull/250

**Comment by chapulina** [comment]
Niiice! It's building on Windows CI, it just has some warnings and failing tests, which I think can be addressed later.

We still need to fix macOS and DCO though.

**Comment by ahcorde** [comment]
@osrf-jenkins retest this please

**Comment by ahcorde** [comment]
@chapulina this PR is targeting `main` should I change the base to `ign-launch4` or `ign-launch2` ? Same question for this other one https://github.com/ignitionrobotics/ign-launch/pull/121

**Comment by chapulina** [comment]
> this PR is targeting main should I change the base to ign-launch4 or ign-launch2 ? 

I see this PR is doing a lot at once, I'd recommend at least moving the gtest version change to its own PR like https://github.com/ignitionrobotics/ign-gazebo/pull/500. And that can be targeted at `ign-launch2`.

I only took a high-level view of the PR and it looks to me that it doesn't change behaviour. If that's indeed the case, I think the whole thing can be targeted at `ign-launch2`. We won't enable Windows CI for that branch, but it helps to be more consistent across branches when forward-porting.

**Comment by scpeters** [comment]
I noticed a windows-related problem with the `cmd*.rb` files when I was testing https://github.com/ignitionrobotics/ign-transport/pull/216. The following lines have some logic for detecting when a string is an absolute or relative path based on whether it starts with `/`, but that is not valid logic for Windows, which has absolute paths that can start with `C:\`

https://github.com/ignitionrobotics/ign-launch/blob/main/src/cmd/cmdlaunch.rb.in#L33-L40

We can put this in an issue if you aren't planning to address the ruby code in this PR

**Comment by j-rivero** [comment]
> We can put this in an issue if you aren't planning to address the ruby code in this PR

Let's do it to help with merging this as soon as possible to gain CI on Windows on other changes: https://github.com/ignitionrobotics/ign-launch/issues/129

**Comment by j-rivero** [comment]
Compilation on Windows is working again, although tests needs attention.

**Review by chapulina — APPROVED** [review]
LGTM! We can address the test failures later. DCO needs to be fixed.

**Comment by j-rivero** [comment]
> LGTM! We can address the test failures later. DCO needs to be fixed.

I'll squash-merge the pull request and will set the right signed-off.

**Pull request merged**
