### PR TITLE
Add support for specifying topics to record

### PR DESCRIPTION
**Pull request by nkoenig**
Requires: https://github.com/ignitionrobotics/ign-gazebo/pull/315

Example usage:
```

    <record>
      <enabled>true</enabled>
      <!-- This path is used by cloudsim, please do not change -->
      <path>/tmp/ign/logs</path>
      <overwrite>true</overwrite>
      <record_topic>/world/.*</record_topic>
    </record>
```

Useful PR to prevent spamming: https://github.com/ignitionrobotics/ign-transport/pull/164
Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
changes look good. Triggered new jenkins builds as there was an issue with homebrew

**Comment by chapulina** [comment]
@osrf-jenkins run tests again

**Comment by iche033** [comment]
looks like we need a release of ign-gazebo2 first in order for CI to be green

**Comment by chapulina** [comment]
@osrf-jenkins run tests now that `ign-gazebo 2.25.0` is out

**Review by chapulina — APPROVED** [review]

**Pull request merged**
