### PR TITLE
Update Dome versions

### PR DESCRIPTION
**Pull request by nkoenig**
Update gazebo and transport versions for Dome.

Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
This requires:

- [ ] https://github.com/ignitionrobotics/ign-gazebo/pull/262
- [ ] An `ign-gazebo4` nightly release with :point_up: 
- [ ] A `homebrew-simulation` commit update

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
I think we just need these:

* https://github.com/osrf/homebrew-simulation/pull/1063
* https://github.com/ignitionrobotics/ign-dome/pull/2

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
Ok, all CI is happy except:
 * ubuntu_auto: needs patching, running the test for the fix here [Build Status](https://build.osrfoundation.org/job/ignition_launch-ci-pr_any-ubuntu_auto-amd64/281/)
 * Action for Focal: it requires fixes from ign-launch2 branch. It's going to be much easier to merge this first and do the forward port after.

**Comment by j-rivero** [comment]
There is only one cmake warning left in the CI that require a bit more of work to be fixed. 
Ubuntu should be fixed after https://github.com/ignition-tooling/release-tools/pull/259. Ready  to merge.

**Comment by chapulina** [comment]
Copied the fix from https://github.com/bombela/backward-cpp/pull/165 on f52c9f3 to fix the Focal build.

**Pull request merged**
